### ISSUE TITLE
wrong type return on plugin

### ISSUE THREAD

**Issue by ching631108** [inway/flutter_ringtone_player#1]
on flutter_ringtone_player/android/src/main/java/io/inway/ringtone/player/FlutterRingtonePlayerPlugin.java:45

 
                if (!call.hasArgument("android")) {
                    return result.notImplemented();
                }

this funcion "onMethodCall" should return void, but here return result.notImplemented();

when I use this code ,my flutter obj can't run on Android.

I tried to fix it to
 
                if (!call.hasArgument("android")) {
                    result.notImplemented();
                    return;
                }

It will work will.

I am poor with github, so I didn't know how to Pull requests. I believe other one can do it better. thanks.

**Comment by SPodjasek** [comment]
Thank you for this report, it should be fixed now.
