### ISSUE TITLE
Deprecate warning

### ISSUE THREAD

**Issue by andzejsw** [inway/flutter_ringtone_player#14]
`Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_ringtone_player-2.0.0\android\src\main\java\io\inway\ringtone\player\FlutterRingtonePlayerPlugin.java uses or overrides a deprecated API.`
Everything works fine, but there is warning visible. Need to fix this, before it causes some more trouble.

**Comment by madatr** [comment]
+1 this

**Comment by SPodjasek** [comment]
Any details about API this note references to?

**Comment by madatr** [comment]
Hi, sorry for the delay in the reply.

Recompiling with: `-Xlint:deprecation ` By adding it to build.gradle here: 

`allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
        }
    }   
}`

The output is:

`/.......//flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ringtone_player-2.0.0/android/src/main/java/io/inway/ringtone/player/FlutterRingtonePlayerPlugin.java:100: warning: [deprecation] setStreamType(int) in Ringtone has been deprecated
                        ringtone.setStreamType(AudioManager.STREAM_ALARM);
                                ^                                       
1 warning       `

This is in the java plugin file, i'm not too proficient in java but what i've found is that: setStreamType was deprecated in API Level 21+ and according to [this](https://developer.android.com/reference/android/media/Ringtone), the use of streams is deprecated.

**Comment by serkanayaz** [comment]
+1 this

**Comment by madatr** [comment]
You should prioritise this as I was testing on an android phone with OS 6.1.0 and it was working fine but testing on Android OS 7.0.0 it does not work, I suppose the function was removed in that version which means that the package does not work any more.

**Comment by SPodjasek** [comment]
@madatr @andzejsw After merging #21 is it still a thing?

**Comment by andzejsw** [comment]
> @madatr @andzejsw After merging #21 is it still a thing?

Yes. Haven't worked on deprecation warning issue.

**Comment by andzejsw** [comment]
> @madatr @andzejsw After merging #21 is it still a thing?

Adding "android.useDeprecatedNdk=true" to "gradle.properties" removes warning. So problem should be there.
