### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method play on channel flutter_ringtone_player)

### ISSUE THREAD

**Issue by Bharavi26** [inway/flutter_ringtone_player#16]
**flutter_ringtone_player: 2.0.0**
already did flutter clean and get , but still getting missingpluginexception

Unhandled Exception: MissingPluginException(No implementation found for method play on channel flutter_ringtone_player)
![ringtoneplayer](https://user-images.githubusercontent.com/36761436/103459339-afeb3e80-4d34-11eb-8502-964445aeb864.png)

**Comment by 91priyansh** [comment]
@Bharavi26 need to register plugin in appplication.kt if you are using this in firebase backgroundmessagehandler

**Comment by mmustafavistech** [comment]
any working on this?

**Comment by 91priyansh** [comment]
i have added these lines in my application.kt file..

if (!registry!!.hasPlugin("io.inway.ringtone.player")) {
            FlutterRingtonePlayerPlugin.registerWith(registry!!.registrarFor("io.inway.ringtone.player.FlutterRingtonePlayerPlugin"))
        }

and do not forget to import import io.inway.ringtone.player.FlutterRingtonePlayerPlugin

if you wanted to see full file link is here https://github.com/91priyansh/facetime/blob/main/android/app/src/main/kotlin/com/facetime/face_time/facetime/Application.kt

**Comment by hemabhravee** [comment]
I'm facing the same issue, and I'm not using firebase backgroundmessagehandler. Any suggestions?

**Comment by karebet** [comment]
> > I'm facing the same issue, and I'm not using firebase backgroundmessagehandler. Any suggestions?

@hemabhravee 
if you see a reference from @91priyansh . you see a Firebase Plugin, if you don't use Firebase you just delete it. 
example :

```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.plugin.common.PluginRegistry
import io.inway.ringtone.player.FlutterRingtonePlayerPlugin

class MainActivity: FlutterActivity(),PluginRegistry.PluginRegistrantCallback  {
     override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.inway.ringtone.player")) {
            FlutterRingtonePlayerPlugin.registerWith(registry!!.registrarFor("io.inway.ringtone.player.FlutterRingtonePlayerPlugin"))
        }
    }
}
```

**Comment by nibiru2O12** [comment]
experienced this on windows.

try enabling developer mode: 

run: start ms-settings:developers

**Comment by chitraarasu** [comment]
Just close the app and re-run the app. It would work
