### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by ricardogottheil** [inway/flutter_ringtone_player#19]
It's not an issue. But are you considering supporting Null Safety?

**Comment by andzejsw** [comment]
> It's not an issue. But are you considering supporting Null Safety?

I have created new PR: https://github.com/inway/flutter_ringtone_player/pull/21
Hope it will be implemented soon. Already tested it and it works. Implements null safety logic and migration to Flutter 2.0 + AndroidX packages migration.

**Comment by SPodjasek** [comment]
Thanks to @andzejsw work this issue should now be closed.
