### ISSUE TITLE
Module 'flutter_ringtone_player' not found on iOS

### ISSUE THREAD

**Issue by Zervandez** [inway/flutter_ringtone_player#30]
I get the following error when trying to run the app from XCode.

**Comment by SPodjasek** [comment]
Sadly, as for now I'm unable to verify this issue as I don't have any usable Apple device to test on...

**Comment by pjarnfelt** [comment]
I had this issue with Pod files not loaded in. Make sure you open the .xcworkspace and not the .xcodeproj. Also install pod files with `pod install` in the iOS folder. Hope it helps.
