### ISSUE TITLE
W/MediaPlayer(14698): java.io.FileNotFoundException: No content provider: /data/user/0/com.example.apk/cache/assets/sounds/ringtone.mp3 

### ISSUE THREAD

**Issue by 0neCigarettes** [inway/flutter_ringtone_player#34]

**Comment by 0neCigarettes** [comment]
How i can solve this?

my code: 

FlutterRingtonePlayer.play(
          fromAsset: "assets/sounds/ringtone.mp3",
          volume: 1.0,
          looping: false,
          asAlarm: true);

**Comment by suhaib-raadan** [comment]
Hi, Im also facing the same issue .Sound plays but the error found in console .Do You know the reason ?

**Comment by 0neCigarettes** [comment]
Try add path source on pubspec.yaml
:# To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/backgrounds/
    - assets/sounds/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

And clean your flutter project
