### ISSUE TITLE
Notification Sound Not Stopped After App is Killed or Foreground

### ISSUE THREAD

**Issue by munishkumarwinapp** [inway/flutter_ringtone_player#36]
Notification sound stop working fine in app with out kill , but after kill the app i'm not able to stop notification sound Please help me

**Comment by shrutika-tatkare-apptware** [comment]
same issue. do you found solution ?

**Comment by munishkumarwinapp** [comment]
> > same issue. do you found solution ?
> 
> > same issue. do you found solution ?
> > Not yet last two i hold that task

if any idea let me know

**Comment by fisforfaheem** [comment]
Please email the apckage make he is not active

**Comment by SPodjasek** [comment]
@fisforfaheem He's active but has many other projects to attend to right now. 
This is free software, and by free, it means freedom to explore, use and modify - it doesn't mean you get a free developer at your service to fix any issue that occurs under your specific circumstances. 
Don't get me wrong - it's great that you've found this package useful, but it's simply impossible to investigate and fix all issues posted here in my free time.

**Comment by SPodjasek** [comment]
Regarding this issue, a possible fix is probably in #8 - but the original contributor hasn't been able to rebase this PR to the current HEAD yet, and without that, I'm unable to merge it.

**Comment by SPodjasek** [comment]
Duplicate of #7

**Comment by fisforfaheem** [comment]
Thanks, I am sorry If I hurt someone's heart, I am new to Github had no
idea!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/11/22,
02:39:49
