### ISSUE TITLE
Couldn't be able to stop ringtone in IOS.  Any clue, when would this gets addressed. 

### ISSUE THREAD

**Issue by vasuravada** [inway/flutter_ringtone_player#37]

**Comment by pranavo72bex** [comment]
I am unable to stop sound when app is resuming from background to foreground
  FlutterRingtonePlayer.stop();

**Comment by hafidzaini** [comment]
cant (immediately) stop the sound too on ios, on android working fine

**Comment by BhavinPanchal001** [comment]
Is there any solution for this issue!!
