### ISSUE TITLE
Please Fix this pressing issue and add flutter 3.3.7 support

### ISSUE THREAD

**Issue by fisforfaheem** [inway/flutter_ringtone_player#38]
Note: /Users/4edoc/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ringtone_player-3.2.0/android/src/main/java/io/inway/ringtone/player/FlutterRingtonePlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by SPodjasek** [comment]
What your're quoting is just a note, not an error or even a warning.
Also what do you mean by 'add flutter 3.3.7' support?
