### ISSUE TITLE
Not able to play sound in ios.

### ISSUE THREAD

**Issue by jitendramistry1** [inway/flutter_ringtone_player#44]
How to play ios sound when app is background. 
I know its not implemeted in your plugin but i'm curious to know when you going to implement this feature.
Thanks in advance.

**Comment by SPodjasek** [comment]
I don't plan to implement this feature. 

The primary purpose of this package is to play notification sounds while the app is in the foreground, as by the time it was written, FlutterFire FCM implementation could not display notifications on received messages while the app was active - if I remember correctly.

Even today, looking at the documentation, you can find this:

> The default behavior on all platforms is to display a notification only when the app is in the background or terminated. If required, you can override this behavior by following the [Foreground Notifications](https://firebase.flutter.dev/docs/messaging/notifications#foreground-notifications) documentation.

So, it was meant to give your user some sound notification when a new dialog or toast appears.
Now I see you can use foreground notifications with FlutterFire messaging package, as from version 6.0.13 it works nicely with `flutter_local_notifications` package.

**Comment by shrutika-tatkare-apptware** [comment]
I am able to play sound but not able to keep sound in loop

**Comment by shrutika-tatkare-apptware** [comment]
Hey. Sound is playing but not able to loop it. can you tell me reason ?

**Comment by ehsan097** [comment]
Hi,Im also facing the same issue on iOS.Sound plays once but not in loop.Do You know the reason ?

**Comment by shrutika-tatkare-apptware** [comment]
Everyone is facing same issue. Please let us know better solution for this. if this plugin not supports then Let me know another one. It's blocker for me really😔😔

**Comment by khanhandpad** [comment]
can not loop the sound in ios, just play once
its big issue, pls help me have a look, thanks
