### ISSUE TITLE
FlutterRingtonePlayer not working in Samsung galaxy s22 ultra

### ISSUE THREAD

**Issue by sumitagadhvi** [inway/flutter_ringtone_player#45]
hello, 
   i have used FlutterRingtonePlayer library to play ringtone when video call receiving screen gets open in device.
but  one of our client facing issue in Samsung galaxy s22 ultra. it is not playing ringtone in this device.
i have used like this.

`FlutterRingtonePlayer.play(fromAsset: "assets/alert.mp3");`

can any one tell me what is problem there?

**Comment by SPodjasek** [comment]
Is this the only device that is not working for you?
Unfortunately I don't have such device to confirm this issue, and on devices I do own it works. Maybe someone else can confirm and investigate?
