### ISSUE TITLE
Member not found: 'FlutterRingtonePlayer.play'.

### ISSUE THREAD

**Issue by katunins** [inway/flutter_ringtone_player#66]
flutter_ringtone_player: ^4.0.0+1
main.dart

Error:

Failed to build iOS app
Error (Xcode): lib/main.dart:82:25: Error: Member not found: 'FlutterRingtonePlayer.play'.

...
FlutterRingtonePlayer.play(
    android: AndroidSounds.notification,
    ios: IosSounds.sentMessage,
    volume: 0.1, // Android only - API >= 28
    asAlarm: false,
  );
...

IDE: Instance member 'play' can't be accessed using static access

**Comment by katunins** [comment]
should be update doc in pub.dev -> readme

<img width="797" alt="image" src="https://github.com/inway/flutter_ringtone_player/assets/61758341/fab3bb92-cedf-4d8a-a212-834aabc1461f">

**Comment by cnkygmr** [comment]
Yes, I installed the latest version, I have this problem.flutter_ringtone_player: ^4.0.0+1

**Comment by cnkygmr** [comment]
`FlutterRingtonePlayer().play();` right way

**Comment by SPodjasek** [comment]
Sorry missed that during merging one of the latest PRs.

I've just released `v4.0.0+2` which should have proper examples in `README.md`.
