### ISSUE TITLE
flutter_lints should not be dependency

### ISSUE THREAD

**Issue by Dumoulin-Lander** [inway/flutter_ringtone_player#80]
As the header says: I don't know of a reason why this package should depend on the linter. It should probably get moved to a dev dependency so Users of this library are not forced to use the same linter as described here.

**Comment by mustafa-707** [comment]
same here , can we fix it please ? @SPodjasek

**Comment by SPodjasek** [comment]
This was introduced as a part of a bigger PR to upgrade this plugin to Flutter 3.x - I'll move it to `dev_dependencies`
